### ISSUE TITLE
release with semver tag

### ISSUE THREAD

**Issue by alexdelprete** [vegardit/docker-traefik-logrotate#10]
Hi,

first of all thanks for this, it's really helpful. :)

Wanted to ask if you could please create a release version with semver tagging, I'm using [WUD](https://github.com/fmartinou/whats-up-docker) and without the semver tag this container gets an update notification very often because the digest changes using tag `latest`.

Thanks in advance. :)

**Comment by sebthom** [comment]
Hi, I don't see how semver will help you. The image is rebuild regular to include potentially new security updates of the underlying system libraries. If you don't want to update your container that often you couldn't try to configure WUD to only check for image updates every X-days.

**Comment by alexdelprete** [comment]
> I don't see how semver will help you

semver helps because a user can decide to update only on major releases, etc.

> If you don't want to update your container that often you couldn't try to configure WUD to only check for image updates every X-days

can't do it on a single container, you can configure it only for docker instance.

anyway, no problem, if you don't feel the need to apply versions I will simply disable update checking.

Thanks anyway for replying.

**Comment by iLuckyW** [comment]
I know this issue is closed, but I wanted to echo @alexdelprete’s point. From an operations perspective, having a specific version number to reference is vital for reproducibility.

Without sem ver, it's impossible to guarantee that a deployment made today will behave the same way in two months. If the image updates under a generic tag (like latest), it can introduce 'silent' breaking changes that are difficult to debug. Tagged releases allow pinning to a known-working state.
