### ISSUE TITLE
Feature Request: Change owner of log file

### ISSUE THREAD

**Issue by modem7** [vegardit/docker-traefik-logrotate#13]
Would it be possible to have the ability to change the owner of the log file after rotation? 

Currently, it defaults to root:root as that's what the container runs as. 

My Traefik logs are currently owned by a different user and group. 

An env var to override the `create 0644 root root` section would probably do it quite nicely.

**Comment by sebthom** [comment]
Please give it a try.

**Comment by modem7** [comment]
Works great, thank you!

**Comment by sebthom** [comment]
As of logrotate [3.18](https://github.com/logrotate/logrotate/releases/tag/3.18.0) it should be possible to use numerical gid/uid instead of names. Alpine 3 currently comes with version 3.21 so it should actually work. what is the error message you get when you use uid/gid instead of username/groupname?

**Comment by niawag** [comment]
Great, thanks!

**Comment by sebthom** [comment]
If that works for you we can generalize it and extend the run script.

**Comment by niawag** [comment]
Thanks for the idea, I've started to work on it from inside the container and the first command (addgroup) already raised a problem: what to do if the desired GID (or UID) is already used ? I think the "standard" docker approach for this is by using S6-overlay. Images built by LinuxServer are using it, here is the script adding the user: https://github.com/linuxserver/docker-baseimage-alpine/blob/466a927f405f69aa6aea77d7ffa42b75de3ed671/root/etc/s6-overlay/s6-rc.d/init-adduser/run#L5
If you're willing to go this way I think there is two approaches: 
- extract the minimum needed from linuxserver to perform just that
- use linuxserver alpine base image instead of original alpine image
The first option may be optimized but may required a bit of work, the second seems more straightforward. What do you think ?

**Comment by sebthom** [comment]
I fixed it with https://github.com/vegardit/docker-traefik-logrotate/commit/3364294480920525aafb6f476a6f8243f3457723 If it is not sufficient for your use case please open a separate issue.
